ConfigVersion: 1.4
#############################################################################################################
#                          _             _____    _          _                                              #
#          /\             | |           |  __ \  (_)        | |                                             #
#         /  \     _   _  | |_    ___   | |__) |  _    ___  | | __  _   _   _ __                            #
#        / /\ \   | | | | | __|  / _ \  |  ___/  | |  / __| | |/ / | | | | | '_ \                           #
#       / ____ \  | |_| | | |_  | (_) | | |      | | | (__  |   <  | |_| | | |_) |                          #
#      /_/    \_\  \__,_|  \__|  \___/  |_|      |_|  \___| |_|\_\  \__,_| | .__/                           #
#                                                                          | |                              #
#                                                                          |_|                              #
#############################################################################################################
# By: BUTTERFIELD8 & The Zircon Network                                                                     #
# Discord: https://discord.gg/ncHH4FP                                                                       #
#############################################################################################################

#Message Prefix
msgPrefix: "<gray>[<gradient:#AA00FF:#FF55FF>Auto<italic>Pickup</italic></gradient><gray>]"

#Toggle Message - /auto
msgAutoPickupEnable: "<gray>You have <green>enabled <gray>auto pickup."
msgAutoPickupDisable: "<gray>You have <red>disabled <gray>auto pickup."

#Toggle Message - /autosmelt
msgAutoSmeltEnable: "<gray>You have <green>enabled <gray>auto smelt."
msgAutoSmeltDisable: "<gray>You have <red>disabled <gray>auto smelt."

#Toggle Message - /drops
msgAutoMobDropsEnable: "<gray>You have <green>enabled <gray>auto drops."
msgAutoMobDropsDisable: "<gray>You have <red>disabled <gray>auto drops."

#Additional toggling messages
msgAutoEnable: "<gray>Auto pickup has been automatically <green>enabled<gray>."
doAutoEnableMSG: true
msgEnabledJoinMSG: "<gray>Auto pickup has been automatically <green>enabled<gray>."
doEnabledOnJoinMSG: true

#Reload Config Message
msgReload: "<red>Reloaded Config"

#Full Inventory Message
msgFullInv: "<gray>Your inventory is full!"
doFullInvMSG: true
titlebar:
  doTitleBar: false
  line1: "<red>Warning"
  line2: "<gray>Inventory is full!"

#This is most useful for prison servers! -- This setting is not normally recommended
#This feature voids any extra blocks broken when /auto is enabled and the inventory is full!
voidOnFullInv: false

#If set to true AutoPickup will ignore XP drop calculations from when using a silk spawner plugin.
usingSilkSpawnerPlugin: true

#If set to true mobs will naturally drop XP
ignoreMobXPDrops: false

#Please does not have permission
msgNoperms: "<red>You don't have permission to use this command"

#Require Permissions | Do players require permission to run commands?
requirePerms:
  autopickup: true
  auto-reload: true
